// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.32.1

package io.littlehorse.sdk.common.proto;

@com.google.protobuf.Generated
public interface PutVariableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.PutVariableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The ID of the Variable to modify. Note that the VariableId contains the WfRunId,
   * the number of the owning ThreadRun, and the name of the Variable.
   * </pre>
   *
   * <code>.littlehorse.VariableId id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   * The ID of the Variable to modify. Note that the VariableId contains the WfRunId,
   * the number of the owning ThreadRun, and the name of the Variable.
   * </pre>
   *
   * <code>.littlehorse.VariableId id = 1;</code>
   * @return The id.
   */
  io.littlehorse.sdk.common.proto.VariableId getId();
  /**
   * <pre>
   * The ID of the Variable to modify. Note that the VariableId contains the WfRunId,
   * the number of the owning ThreadRun, and the name of the Variable.
   * </pre>
   *
   * <code>.littlehorse.VariableId id = 1;</code>
   */
  io.littlehorse.sdk.common.proto.VariableIdOrBuilder getIdOrBuilder();

  /**
   * <pre>
   * The new value for the Variable.
   * </pre>
   *
   * <code>.littlehorse.VariableValue value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <pre>
   * The new value for the Variable.
   * </pre>
   *
   * <code>.littlehorse.VariableValue value = 2;</code>
   * @return The value.
   */
  io.littlehorse.sdk.common.proto.VariableValue getValue();
  /**
   * <pre>
   * The new value for the Variable.
   * </pre>
   *
   * <code>.littlehorse.VariableValue value = 2;</code>
   */
  io.littlehorse.sdk.common.proto.VariableValueOrBuilder getValueOrBuilder();
}
